<?php	defined ( 'IN_KEKE' ) or exit ( 'Access Denied' );
$strUrl ="index.php?do=user&view=finance&op=rechargelog";
$intPagesize and $strUrl .="&intPagesize=".intval($intPagesize);
$intOrderId and $strUrl .= "&intOrderId=".intval($intOrderId);
$strOrderType and $strUrl .= "&strOrderType=".strval($strOrderType);
$strOrder and $strUrl .="&strOrder=".strval($strOrder);
$objChargeT = keke_table_class::get_instance('witkey_order_charge');
$arrOrderType = keke_glob_class::get_charge_type();
$arrBank = keke_glob_class::get_bank();
$arrStatus = keke_order_class::get_order_status();
$arrOrder = array ('order_id desc' =>'充值单号降序', 'order_id asc' => '充值单号升序', 'pay_time desc' =>'充值时间降序', 'pay_time asc' =>'充值时间升序');
$page and $intPage = intval($page);
$intPage = intval ( $intPage ) ? $intPage : 1;
$intPagesize = intval ( $intPagesize ) ? $intPagesize : 10;
$strWhere = ' 1 = 1  and uid = '.intval($gUid);
$intOrderId && $intOrderId != '' and $strWhere .= " and order_id = '$intOrderId' ";
$strOrderType and $strWhere .= " and order_type = '$strOrderType' ";
$floatCountCashs =kekezu::get_table_data(" sum(pay_money) as cash,order_status ","witkey_order_charge"," $strWhere ",""," order_status","","order_status");
$strOrder and $strWhere .= " order by $strOrder " or $strWhere .= " order by order_id desc ";
$arrDatas = $objChargeT->get_grid ( $strWhere, $strUrl, $intPage, $intPagesize, null,null,null);
$arrChargeLists = $arrDatas ['data'];
$strPages = $arrDatas ['pages'];
