<?php	defined ( 'IN_KEKE' ) or exit ( 'Access Denied' );
$strUrl ="index.php?do=user&view=finance&op=withdrawlog";
$intPagesize and $strUrl .="&intPagesize=".intval($intPagesize);
$intWithdrawId and $strUrl .= "&intWithdrawId=".intval($intWithdrawId);
$obWithdrawT = keke_table_class::get_instance('witkey_withdraw');
$arrStatus  = keke_glob_class::withdraw_status();
$page and $intPage = intval($page);
$intPage = intval ( $intPage ) ? $intPage : 1;
$intPagesize = intval ( $intPagesize ) ? $intPagesize : 10;
$arrBank = keke_glob_class::get_bank();
$arrOnline   = keke_glob_class::get_online_pay();
$arrBank = array_merge($arrOnline,$arrBank);
$strWhere = ' 1 = 1  and uid = '.intval($gUid);
$intWithdrawId && $intWithdrawId != '' and $strWhere .= " and withdraw_id = '$intWithdrawId' ";
$floatCountCashs = kekezu::get_table_data(" sum(withdraw_cash) as cash,withdraw_status ","witkey_withdraw"," $strWhere ",""," withdraw_status","","withdraw_status");
 $strWhere .= " order by withdraw_id desc ";
$arrDatas = $obWithdrawT->get_grid ( $strWhere, $strUrl, $intPage, $intPagesize, null,null,null);
$arrWithdrawLists = $arrDatas ['data'];
$strPages = $arrDatas ['pages'];
