<?php
class Keke_witkey_feed_class{
	public $_db;
	public $_tablename;
	public $_dbop;
	public $_feed_id;	public $_obj_id;	public $_obj_link;	public $_feedtype;	public $_uid;	public $_username;	public $_icon;	public $_title;	public $_feed_desc;	public $_feed_pic;	public $_feed_time;	public $_ext_data;
	public $_cache_config = array ('is_cache' => 0, 'time' => 0 );
	public $_replace=0;
	public $_where;
	function  keke_witkey_feed_class(){		$this->_db = new db_factory ( );		$this->_dbop = $this->_db->create(DBTYPE);		$this->_tablename = TABLEPRE."witkey_feed";	}	 
	public function getFeed_id(){		return $this->_feed_id ;	}	public function getObj_id(){		return $this->_obj_id ;	}	public function getObj_link(){		return $this->_obj_link ;	}	public function getFeedtype(){		return $this->_feedtype ;	}	public function getUid(){		return $this->_uid ;	}	public function getUsername(){		return $this->_username ;	}	public function getIcon(){		return $this->_icon ;	}	public function getTitle(){		return $this->_title ;	}	public function getFeed_desc(){		return $this->_feed_desc ;	}	public function getFeed_pic(){		return $this->_feed_pic ;	}	public function getFeed_time(){		return $this->_feed_time ;	}	public function getExt_data(){		return $this->_ext_data ;	}	public function getWhere(){		return $this->_where ;	}	public function getCache_config() {		return $this->_cache_config;	}
	public function setFeed_id($value){		$this->_feed_id = $value;	}	public function setObj_id($value){		$this->_obj_id = $value;	}	public function setObj_link($value){		$this->_obj_link = $value;	}	public function setFeedtype($value){		$this->_feedtype = $value;	}	public function setUid($value){		$this->_uid = $value;	}	public function setUsername($value){		$this->_username = $value;	}	public function setIcon($value){		$this->_icon = $value;	}	public function setTitle($value){		$this->_title = $value;	}	public function setFeed_desc($value){		$this->_feed_desc = $value;	}	public function setFeed_pic($value){		$this->_feed_pic = $value;	}	public function setFeed_time($value){		$this->_feed_time = $value;	}	public function setExt_data($value){		$this->_ext_data = $value;	}	public function setWhere($value){		$this->_where = $value;	}	public function setCache_config($_cache_config) {		$this->_cache_config = $_cache_config;	}
	public  function __set($property_name, $value) {
		$this->$property_name = $value;
	}
	public function __get($property_name) {
		if (isset ( $this->$property_name )) {
			return $this->$property_name;
		} else {
			return null;
		}
	}
		function create_keke_witkey_feed(){		$data =  array();		if(!is_null($this->_feed_id)){			$data['feed_id']=$this->_feed_id;		}		if(!is_null($this->_obj_id)){			$data['obj_id']=$this->_obj_id;		}		if(!is_null($this->_obj_link)){			$data['obj_link']=$this->_obj_link;		}		if(!is_null($this->_feedtype)){			$data['feedtype']=$this->_feedtype;		}		if(!is_null($this->_uid)){			$data['uid']=$this->_uid;		}		if(!is_null($this->_username)){			$data['username']=$this->_username;		}		if(!is_null($this->_icon)){			$data['icon']=$this->_icon;		}		if(!is_null($this->_title)){			$data['title']=$this->_title;		}		if(!is_null($this->_feed_desc)){			$data['feed_desc']=$this->_feed_desc;		}		if(!is_null($this->_feed_pic)){			$data['feed_pic']=$this->_feed_pic;		}		if(!is_null($this->_feed_time)){			$data['feed_time']=$this->_feed_time;		}		if(!is_null($this->_ext_data)){			$data['ext_data']=$this->_ext_data;		}		return $this->_feed_id = $this->_db->inserttable($this->_tablename,$data,1,$this->_replace);	}
		function edit_keke_witkey_feed(){		$data =  array();		if(!is_null($this->_feed_id)){			$data['feed_id']=$this->_feed_id;		}		if(!is_null($this->_obj_id)){			$data['obj_id']=$this->_obj_id;		}		if(!is_null($this->_obj_link)){			$data['obj_link']=$this->_obj_link;		}		if(!is_null($this->_feedtype)){			$data['feedtype']=$this->_feedtype;		}		if(!is_null($this->_uid)){			$data['uid']=$this->_uid;		}		if(!is_null($this->_username)){			$data['username']=$this->_username;		}		if(!is_null($this->_icon)){			$data['icon']=$this->_icon;		}		if(!is_null($this->_title)){			$data['title']=$this->_title;		}		if(!is_null($this->_feed_desc)){			$data['feed_desc']=$this->_feed_desc;		}		if(!is_null($this->_feed_pic)){			$data['feed_pic']=$this->_feed_pic;		}		if(!is_null($this->_feed_time)){			$data['feed_time']=$this->_feed_time;		}		if(!is_null($this->_ext_data)){			$data['ext_data']=$this->_ext_data;		}		if($this->_where){			return $this->_db->updatetable($this->_tablename,$data,$this->getWhere());		}		else{			$where = array('feed_id' => $this->_feed_id);			return $this->_db->updatetable($this->_tablename,$data,$where);		}	}
		function query_keke_witkey_feed($is_cache=0, $cache_time=0){		if($this->_where){			$sql = "select * from $this->_tablename where ".$this->_where;		}		else{			$sql = "select * from $this->_tablename";		}		if ($is_cache) {			$this->_cache_config ['is_cache'] = $is_cache;		}		if ($cache_time) {			$this->_cache_config ['time'] = $cache_time;		}		if ($this->_cache_config ['is_cache']) {			if (CACHE_TYPE) {				$keke_cache = new keke_cache_class ( CACHE_TYPE );				$id = $this->_tablename . ($this->_where?"_" .substr(md5 ( $this->_where ),0,6):'');				$data = $keke_cache->get ( $id );				if ($data) {					return $data;				} else {					$res = $this->_dbop->query ( $sql );					$keke_cache->set ( $id, $res,$this->_cache_config['time'] );					$this->_where = "";					return $res;				}			}		}else{			$this->_where = "";			return  $this->_dbop->query ( $sql );		}	}
		function count_keke_witkey_feed(){		if($this->_where){			$sql = "select count(*) as count from $this->_tablename where ".$this->_where;		}		else{			$sql = "select count(*) as count from $this->_tablename";		}		$this->_where = "";		return $this->_dbop->getCount($sql);	}
		function del_keke_witkey_feed(){		if($this->_where){			$sql = "delete from $this->_tablename where ".$this->_where;		}		else{			$sql = "delete from $this->_tablename where feed_id = $this->_feed_id ";		}		$this->_where = "";		return $this->_dbop->execute($sql);	}
}
?>