<?php
  class Keke_witkey_mark_class{
        public $_db;
        public $_tablename;
	    public $_dbop;
	    	 public $_mark_id;  		 public $_model_code; 		 public $_origin_id; 		 public $_obj_id; 		 public $_obj_cash; 		 public $_mark_status; 		 public $_mark_content; 		 public $_mark_time; 		 public $_uid; 		 public $_username; 		 public $_mark_max_time; 		 public $_by_uid; 		 public $_by_username; 		 public $_aid; 		 public $_aid_star; 		 public $_mark_value; 		 public $_mark_type; 		 public $_mark_count; 
	    public $_cache_config = array ('is_cache' => 0, 'time' => 0 );
	    public $_replace=0;  
	    public $_where;      
	     function  keke_witkey_mark_class(){ 			 $this->_db = new db_factory ( );			 $this->_dbop = $this->_db->create(DBTYPE);			 $this->_tablename = TABLEPRE."witkey_mark";		 }	    
	    		public function getMark_id(){			 return $this->_mark_id ;		}		public function getModel_code(){			 return $this->_model_code ;		}		public function getOrigin_id(){			 return $this->_origin_id ;		}		public function getObj_id(){			 return $this->_obj_id ;		}		public function getObj_cash(){			 return $this->_obj_cash ;		}		public function getMark_status(){			 return $this->_mark_status ;		}		public function getMark_content(){			 return $this->_mark_content ;		}		public function getMark_time(){			 return $this->_mark_time ;		}		public function getUid(){			 return $this->_uid ;		}		public function getUsername(){			 return $this->_username ;		}		public function getMark_max_time(){			 return $this->_mark_max_time ;		}		public function getBy_uid(){			 return $this->_by_uid ;		}		public function getBy_username(){			 return $this->_by_username ;		}		public function getAid(){			 return $this->_aid ;		}		public function getAid_star(){			 return $this->_aid_star ;		}		public function getMark_value(){			 return $this->_mark_value ;		}		public function getMark_type(){			 return $this->_mark_type ;		}		public function getMark_count(){			 return $this->_mark_count ;		}		public function getWhere(){			 return $this->_where ;		}		public function getCache_config() {			return $this->_cache_config;		}
	    		public function setMark_id($value){ 			 $this->_mark_id = $value;		}		public function setModel_code($value){ 			 $this->_model_code = $value;		}		public function setOrigin_id($value){ 			 $this->_origin_id = $value;		}		public function setObj_id($value){ 			 $this->_obj_id = $value;		}		public function setObj_cash($value){ 			 $this->_obj_cash = $value;		}		public function setMark_status($value){ 			 $this->_mark_status = $value;		}		public function setMark_content($value){ 			 $this->_mark_content = $value;		}		public function setMark_time($value){ 			 $this->_mark_time = $value;		}		public function setUid($value){ 			 $this->_uid = $value;		}		public function setUsername($value){ 			 $this->_username = $value;		}		public function setMark_max_time($value){ 			 $this->_mark_max_time = $value;		}		public function setBy_uid($value){ 			 $this->_by_uid = $value;		}		public function setBy_username($value){ 			 $this->_by_username = $value;		}		public function setAid($value){ 			 $this->_aid = $value;		}		public function setAid_star($value){ 			 $this->_aid_star = $value;		}		public function setMark_value($value){ 			 $this->_mark_value = $value;		}		public function setMark_type($value){ 			 $this->_mark_type = $value;		}		public function setMark_count($value){ 			 $this->_mark_count = $value;		}		public function setWhere($value){ 			 $this->_where = $value;		}		public function setCache_config($_cache_config) {			 $this->_cache_config = $_cache_config; 		}
    	   public  function __set($property_name, $value) {
		 		$this->$property_name = $value; 
			}
			public function __get($property_name) { 
				if (isset ( $this->$property_name )) { 
					return $this->$property_name; 
				} else { 
					return null; 
				} 
			}
	    		function create_keke_witkey_mark(){		 		 $data =  array(); 					if(!is_null($this->_mark_id)){ 				 $data['mark_id']=$this->_mark_id;			}			if(!is_null($this->_model_code)){ 				 $data['model_code']=$this->_model_code;			}			if(!is_null($this->_origin_id)){ 				 $data['origin_id']=$this->_origin_id;			}			if(!is_null($this->_obj_id)){ 				 $data['obj_id']=$this->_obj_id;			}			if(!is_null($this->_obj_cash)){ 				 $data['obj_cash']=$this->_obj_cash;			}			if(!is_null($this->_mark_status)){ 				 $data['mark_status']=$this->_mark_status;			}			if(!is_null($this->_mark_content)){ 				 $data['mark_content']=$this->_mark_content;			}			if(!is_null($this->_mark_time)){ 				 $data['mark_time']=$this->_mark_time;			}			if(!is_null($this->_uid)){ 				 $data['uid']=$this->_uid;			}			if(!is_null($this->_username)){ 				 $data['username']=$this->_username;			}			if(!is_null($this->_mark_max_time)){ 				 $data['mark_max_time']=$this->_mark_max_time;			}			if(!is_null($this->_by_uid)){ 				 $data['by_uid']=$this->_by_uid;			}			if(!is_null($this->_by_username)){ 				 $data['by_username']=$this->_by_username;			}			if(!is_null($this->_aid)){ 				 $data['aid']=$this->_aid;			}			if(!is_null($this->_aid_star)){ 				 $data['aid_star']=$this->_aid_star;			}			if(!is_null($this->_mark_value)){ 				 $data['mark_value']=$this->_mark_value;			}			if(!is_null($this->_mark_type)){ 				 $data['mark_type']=$this->_mark_type;			}			if(!is_null($this->_mark_count)){ 				 $data['mark_count']=$this->_mark_count;			}			 return $this->_mark_id = $this->_db->inserttable($this->_tablename,$data,1,$this->_replace); 		 } 
	    		function edit_keke_witkey_mark(){ 		 		 $data =  array();  					if(!is_null($this->_mark_id)){ 				 $data['mark_id']=$this->_mark_id;			}			if(!is_null($this->_model_code)){ 				 $data['model_code']=$this->_model_code;			}			if(!is_null($this->_origin_id)){ 				 $data['origin_id']=$this->_origin_id;			}			if(!is_null($this->_obj_id)){ 				 $data['obj_id']=$this->_obj_id;			}			if(!is_null($this->_obj_cash)){ 				 $data['obj_cash']=$this->_obj_cash;			}			if(!is_null($this->_mark_status)){ 				 $data['mark_status']=$this->_mark_status;			}			if(!is_null($this->_mark_content)){ 				 $data['mark_content']=$this->_mark_content;			}			if(!is_null($this->_mark_time)){ 				 $data['mark_time']=$this->_mark_time;			}			if(!is_null($this->_uid)){ 				 $data['uid']=$this->_uid;			}			if(!is_null($this->_username)){ 				 $data['username']=$this->_username;			}			if(!is_null($this->_mark_max_time)){ 				 $data['mark_max_time']=$this->_mark_max_time;			}			if(!is_null($this->_by_uid)){ 				 $data['by_uid']=$this->_by_uid;			}			if(!is_null($this->_by_username)){ 				 $data['by_username']=$this->_by_username;			}			if(!is_null($this->_aid)){ 				 $data['aid']=$this->_aid;			}			if(!is_null($this->_aid_star)){ 				 $data['aid_star']=$this->_aid_star;			}			if(!is_null($this->_mark_value)){ 				 $data['mark_value']=$this->_mark_value;			}			if(!is_null($this->_mark_type)){ 				 $data['mark_type']=$this->_mark_type;			}			if(!is_null($this->_mark_count)){ 				 $data['mark_count']=$this->_mark_count;			}			if($this->_where){ 				 return $this->_db->updatetable($this->_tablename,$data,$this->getWhere()); 			 } 			 else{ 				 $where = array('mark_id' => $this->_mark_id); 				 return $this->_db->updatetable($this->_tablename,$data,$where); 			} 		 } 
	    		function query_keke_witkey_mark($is_cache=0, $cache_time=0){ 			 if($this->_where){ 				 $sql = "select * from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "select * from $this->_tablename"; 			 } 			if ($is_cache) {			 $this->_cache_config ['is_cache'] = $is_cache;			}			if ($cache_time) {			 $this->_cache_config ['time'] = $cache_time;			 }			 if ($this->_cache_config ['is_cache']) {			     if (CACHE_TYPE) {					 $keke_cache = new keke_cache_class ( CACHE_TYPE );					 $id = $this->_tablename . ($this->_where?"_" .substr(md5 ( $this->_where ),0,6):'');						$data = $keke_cache->get ( $id );							if ($data) {								return $data; 							} else { 								$res = $this->_dbop->query ( $sql ); 								$keke_cache->set ( $id, $res,$this->_cache_config['time'] ); 					 			$this->_where = ""; 								return $res; 							} 						} 			 }else{			 	$this->_where = ""; 				return  $this->_dbop->query ( $sql ); 			 }		 } 
	    		function count_keke_witkey_mark(){ 			 if($this->_where){ 				 $sql = "select count(*) as count from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "select count(*) as count from $this->_tablename"; 			 } 			 $this->_where = ""; 			 return $this->_dbop->getCount($sql); 		 } 
	    		function del_keke_witkey_mark(){ 			 if($this->_where){ 				 $sql = "delete from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "delete from $this->_tablename where mark_id = $this->_mark_id "; 			 } 			 $this->_where = ""; 			 return $this->_dbop->execute($sql); 		 } 
   }
 ?>