<?php
class Keke_witkey_agreement_class{
	public $_db;
	public $_tablename;
	public $_dbop;
	public $_agree_id;	public $_agree_status;	public $_model_id;	public $_task_id;	public $_work_id;	public $_buyer_uid;	public $_buyer_status;	public $_buyer_accepttime;	public $_buyer_confirmtime;	public $_seller_uid;	public $_seller_status;	public $_seller_accepttime;	public $_seller_confirmtime;	public $_agree_title;	public $_file_ids;	public $_on_time;
	public $_cache_config = array ('is_cache' => 0, 'time' => 0 );
	public $_replace=0;
	public $_where;
	function  keke_witkey_agreement_class(){		$this->_db = new db_factory ( );		$this->_dbop = $this->_db->create(DBTYPE);		$this->_tablename = TABLEPRE."witkey_agreement";	}
	public function getAgree_id(){		return $this->_agree_id ;	}	public function getAgree_status(){		return $this->_agree_status ;	}	public function getModel_id(){		return $this->_model_id ;	}	public function getTask_id(){		return $this->_task_id ;	}	public function getWork_id(){		return $this->_work_id ;	}	public function getBuyer_uid(){		return $this->_buyer_uid ;	}	public function getBuyer_status(){		return $this->_buyer_status ;	}	public function getBuyer_accepttime(){		return $this->_buyer_accepttime ;	}	public function getBuyer_confirmtime(){		return $this->_buyer_confirmtime ;	}	public function getSeller_uid(){		return $this->_seller_uid ;	}	public function getSeller_status(){		return $this->_seller_status ;	}	public function getSeller_accepttime(){		return $this->_seller_accepttime ;	}	public function getSeller_confirmtime(){		return $this->_seller_confirmtime ;	}	public function getAgree_title(){		return $this->_agree_title ;	}	public function getFile_ids(){		return $this->_file_ids ;	}	public function getOn_time(){		return $this->_on_time ;	}	public function getWhere(){		return $this->_where ;	}	public function getCache_config() {		return $this->_cache_config;	}
	public function setAgree_id($value){		$this->_agree_id = $value;	}	public function setAgree_status($value){		$this->_agree_status = $value;	}	public function setModel_id($value){		$this->_model_id = $value;	}	public function setTask_id($value){		$this->_task_id = $value;	}	public function setWork_id($value){		$this->_work_id = $value;	}	public function setBuyer_uid($value){		$this->_buyer_uid = $value;	}	public function setBuyer_status($value){		$this->_buyer_status = $value;	}	public function setBuyer_accepttime($value){		$this->_buyer_accepttime = $value;	}	public function setBuyer_confirmtime($value){		$this->_buyer_confirmtime = $value;	}	public function setSeller_uid($value){		$this->_seller_uid = $value;	}	public function setSeller_status($value){		$this->_seller_status = $value;	}	public function setSeller_accepttime($value){		$this->_seller_accepttime = $value;	}	public function setSeller_confirmtime($value){		$this->_seller_confirmtime = $value;	}	public function setAgree_title($value){		$this->_agree_title = $value;	}	public function setFile_ids($value){		$this->_file_ids = $value;	}	public function setOn_time($value){		$this->_on_time = $value;	}	public function setWhere($value){		$this->_where = $value;	}	public function setCache_config($_cache_config) {		$this->_cache_config = $_cache_config;	}
	public  function __set($property_name, $value) {
		$this->$property_name = $value;
	}
	public function __get($property_name) {
		if (isset ( $this->$property_name )) {
			return $this->$property_name;
		} else {
			return null;
		}
	}
		function create_keke_witkey_agreement(){		$data =  array();		if(!is_null($this->_agree_id)){			$data['agree_id']=$this->_agree_id;		}		if(!is_null($this->_agree_status)){			$data['agree_status']=$this->_agree_status;		}		if(!is_null($this->_model_id)){			$data['model_id']=$this->_model_id;		}		if(!is_null($this->_task_id)){			$data['task_id']=$this->_task_id;		}		if(!is_null($this->_work_id)){			$data['work_id']=$this->_work_id;		}		if(!is_null($this->_buyer_uid)){			$data['buyer_uid']=$this->_buyer_uid;		}		if(!is_null($this->_buyer_status)){			$data['buyer_status']=$this->_buyer_status;		}		if(!is_null($this->_buyer_accepttime)){			$data['buyer_accepttime']=$this->_buyer_accepttime;		}		if(!is_null($this->_buyer_confirmtime)){			$data['buyer_confirmtime']=$this->_buyer_confirmtime;		}		if(!is_null($this->_seller_uid)){			$data['seller_uid']=$this->_seller_uid;		}		if(!is_null($this->_seller_status)){			$data['seller_status']=$this->_seller_status;		}		if(!is_null($this->_seller_accepttime)){			$data['seller_accepttime']=$this->_seller_accepttime;		}		if(!is_null($this->_seller_confirmtime)){			$data['seller_confirmtime']=$this->_seller_confirmtime;		}		if(!is_null($this->_agree_title)){			$data['agree_title']=$this->_agree_title;		}		if(!is_null($this->_file_ids)){			$data['file_ids']=$this->_file_ids;		}		if(!is_null($this->_on_time)){			$data['on_time']=$this->_on_time;		}		return $this->_agree_id = $this->_db->inserttable($this->_tablename,$data,1,$this->_replace);	}
		function edit_keke_witkey_agreement(){		$data =  array();		if(!is_null($this->_agree_id)){			$data['agree_id']=$this->_agree_id;		}		if(!is_null($this->_agree_status)){			$data['agree_status']=$this->_agree_status;		}		if(!is_null($this->_model_id)){			$data['model_id']=$this->_model_id;		}		if(!is_null($this->_task_id)){			$data['task_id']=$this->_task_id;		}		if(!is_null($this->_work_id)){			$data['work_id']=$this->_work_id;		}		if(!is_null($this->_buyer_uid)){			$data['buyer_uid']=$this->_buyer_uid;		}		if(!is_null($this->_buyer_status)){			$data['buyer_status']=$this->_buyer_status;		}		if(!is_null($this->_buyer_accepttime)){			$data['buyer_accepttime']=$this->_buyer_accepttime;		}		if(!is_null($this->_buyer_confirmtime)){			$data['buyer_confirmtime']=$this->_buyer_confirmtime;		}		if(!is_null($this->_seller_uid)){			$data['seller_uid']=$this->_seller_uid;		}		if(!is_null($this->_seller_status)){			$data['seller_status']=$this->_seller_status;		}		if(!is_null($this->_seller_accepttime)){			$data['seller_accepttime']=$this->_seller_accepttime;		}		if(!is_null($this->_seller_confirmtime)){			$data['seller_confirmtime']=$this->_seller_confirmtime;		}		if(!is_null($this->_agree_title)){			$data['agree_title']=$this->_agree_title;		}		if(!is_null($this->_file_ids)){			$data['file_ids']=$this->_file_ids;		}		if(!is_null($this->_on_time)){			$data['on_time']=$this->_on_time;		}		if($this->_where){			return $this->_db->updatetable($this->_tablename,$data,$this->getWhere());		}		else{			$where = array('agree_id' => $this->_agree_id);			return $this->_db->updatetable($this->_tablename,$data,$where);		}	}
		function query_keke_witkey_agreement($is_cache=0, $cache_time=0){		if($this->_where){			$sql = "select * from $this->_tablename where ".$this->_where;		}		else{			$sql = "select * from $this->_tablename";		}		if ($is_cache) {			$this->_cache_config ['is_cache'] = $is_cache;		}		if ($cache_time) {			$this->_cache_config ['time'] = $cache_time;		}		if ($this->_cache_config ['is_cache']) {			if (CACHE_TYPE) {				$keke_cache = new keke_cache_class ( CACHE_TYPE );				$id = $this->_tablename . ($this->_where?"_" .substr(md5 ( $this->_where ),0,6):'');				$data = $keke_cache->get ( $id );				if ($data) {					return $data;				} else {					$res = $this->_dbop->query ( $sql );					$keke_cache->set ( $id, $res,$this->_cache_config['time'] );					$this->_where = "";					return $res;				}			}		}else{			$this->_where = "";			return  $this->_dbop->query ( $sql );		}	}
		function count_keke_witkey_agreement(){		if($this->_where){			$sql = "select count(*) as count from $this->_tablename where ".$this->_where;		}		else{			$sql = "select count(*) as count from $this->_tablename";		}		$this->_where = "";		return $this->_dbop->getCount($sql);	}
		function del_keke_witkey_agreement(){		if($this->_where){			$sql = "delete from $this->_tablename where ".$this->_where;		}		else{			$sql = "delete from $this->_tablename where agree_id = $this->_agree_id ";		}		$this->_where = "";		return $this->_dbop->execute($sql);	}
}
?>