<?php
  class Keke_witkey_plug_class{
        public $_db;
        public $_tablename;
	    public $_dbop;
	    	 public $_plug_id;  		 public $_plug_desc; 		 public $_status; 		 public $_author; 		 public $_on_time; 		 public $_plug_name; 		 public $_submenu_id; 		 public $_plug_code; 
	    public $_cache_config = array ('is_cache' => 0, 'time' => 0 );
	    public $_replace=0;  
	    public $_where;      
	     function  keke_witkey_plug_class(){ 			 $this->_db = new db_factory ( );			 $this->_dbop = $this->_db->create(DBTYPE);			 $this->_tablename = TABLEPRE."witkey_plug";		 }	    
	    		public function getPlug_id(){			 return $this->_plug_id ;		}		public function getPlug_desc(){			 return $this->_plug_desc ;		}		public function getStatus(){			 return $this->_status ;		}		public function getAuthor(){			 return $this->_author ;		}		public function getOn_time(){			 return $this->_on_time ;		}		public function getPlug_name(){			 return $this->_plug_name ;		}		public function getSubmenu_id(){			 return $this->_submenu_id ;		}		public function getPlug_code(){			 return $this->_plug_code ;		}		public function getWhere(){			 return $this->_where ;		}		public function getCache_config() {			return $this->_cache_config;		}
	    		public function setPlug_id($value){ 			 $this->_plug_id = $value;		}		public function setPlug_desc($value){ 			 $this->_plug_desc = $value;		}		public function setStatus($value){ 			 $this->_status = $value;		}		public function setAuthor($value){ 			 $this->_author = $value;		}		public function setOn_time($value){ 			 $this->_on_time = $value;		}		public function setPlug_name($value){ 			 $this->_plug_name = $value;		}		public function setSubmenu_id($value){ 			 $this->_submenu_id = $value;		}		public function setPlug_code($value){ 			 $this->_plug_code = $value;		}		public function setWhere($value){ 			 $this->_where = $value;		}		public function setCache_config($_cache_config) {			 $this->_cache_config = $_cache_config; 		}
    	   public  function __set($property_name, $value) {
		 		$this->$property_name = $value; 
			}
			public function __get($property_name) { 
				if (isset ( $this->$property_name )) { 
					return $this->$property_name; 
				} else { 
					return null; 
				} 
			}
	    		function create_keke_witkey_plug(){		 		 $data =  array(); 					if(!is_null($this->_plug_id)){ 				 $data['plug_id']=$this->_plug_id;			}			if(!is_null($this->_plug_desc)){ 				 $data['plug_desc']=$this->_plug_desc;			}			if(!is_null($this->_status)){ 				 $data['status']=$this->_status;			}			if(!is_null($this->_author)){ 				 $data['author']=$this->_author;			}			if(!is_null($this->_on_time)){ 				 $data['on_time']=$this->_on_time;			}			if(!is_null($this->_plug_name)){ 				 $data['plug_name']=$this->_plug_name;			}			if(!is_null($this->_submenu_id)){ 				 $data['submenu_id']=$this->_submenu_id;			}			if(!is_null($this->_plug_code)){ 				 $data['plug_code']=$this->_plug_code;			}			 return $this->_plug_id = $this->_db->inserttable($this->_tablename,$data,1,$this->_replace); 		 } 
	    		function edit_keke_witkey_plug(){ 		 		 $data =  array();  					if(!is_null($this->_plug_id)){ 				 $data['plug_id']=$this->_plug_id;			}			if(!is_null($this->_plug_desc)){ 				 $data['plug_desc']=$this->_plug_desc;			}			if(!is_null($this->_status)){ 				 $data['status']=$this->_status;			}			if(!is_null($this->_author)){ 				 $data['author']=$this->_author;			}			if(!is_null($this->_on_time)){ 				 $data['on_time']=$this->_on_time;			}			if(!is_null($this->_plug_name)){ 				 $data['plug_name']=$this->_plug_name;			}			if(!is_null($this->_submenu_id)){ 				 $data['submenu_id']=$this->_submenu_id;			}			if(!is_null($this->_plug_code)){ 				 $data['plug_code']=$this->_plug_code;			}			if($this->_where){ 				 return $this->_db->updatetable($this->_tablename,$data,$this->getWhere()); 			 } 			 else{ 				 $where = array('plug_id' => $this->_plug_id); 				 return $this->_db->updatetable($this->_tablename,$data,$where); 			} 		 } 
	    		function query_keke_witkey_plug($is_cache=0, $cache_time=0){ 			 if($this->_where){ 				 $sql = "select * from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "select * from $this->_tablename"; 			 } 			if ($is_cache) {			 $this->_cache_config ['is_cache'] = $is_cache;			}			if ($cache_time) {			 $this->_cache_config ['time'] = $cache_time;			 }			 if ($this->_cache_config ['is_cache']) {			     if (CACHE_TYPE) {					 $keke_cache = new keke_cache_class ( CACHE_TYPE );					 $id = $this->_tablename . ($this->_where?"_" .substr(md5 ( $this->_where ),0,6):'');						$data = $keke_cache->get ( $id );							if ($data) {								return $data; 							} else { 								$res = $this->_dbop->query ( $sql ); 								$keke_cache->set ( $id, $res,$this->_cache_config['time'] ); 					 			$this->_where = ""; 								return $res; 							} 						} 			 }else{			 	$this->_where = ""; 				return  $this->_dbop->query ( $sql ); 			 }		 } 
	    		function count_keke_witkey_plug(){ 			 if($this->_where){ 				 $sql = "select count(*) as count from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "select count(*) as count from $this->_tablename"; 			 } 			 $this->_where = ""; 			 return $this->_dbop->getCount($sql); 		 } 
	    		function del_keke_witkey_plug(){ 			 if($this->_where){ 				 $sql = "delete from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "delete from $this->_tablename where plug_id = $this->_plug_id "; 			 } 			 $this->_where = ""; 			 return $this->_dbop->execute($sql); 		 } 
   }
 ?>