<?php
class Keke_witkey_task_wbzf_class{
	public $_db;
	public $_tablename;
	public $_dbop;
	public $_wbzf_id;	public $_task_id;	public $_wb_platform;	public $_is_focus;	public $_is_comment;	public $_is_at;	public $_repost_url;	public $_wb_content;	public $_wb_img;	public $_at_num;	public $_unit_price;	public $_assign;	public $_pay_amount;	public $_fans_count;	public $_is_repost;
	public $_cache_config = array ('is_cache' => 0, 'time' => 0 );
	public $_replace=0;
	public $_where;
	function  keke_witkey_task_wbzf_class(){		$this->_db = new db_factory ( );		$this->_dbop = $this->_db->create(DBTYPE);		$this->_tablename = TABLEPRE."witkey_task_wbzf";	}	 
	public function getWbzf_id(){		return $this->_wbzf_id ;	}	public function getTask_id(){		return $this->_task_id ;	}	public function getWb_platform(){		return $this->_wb_platform ;	}	public function getIs_focus(){		return $this->_is_focus ;	}	public function getIs_comment(){		return $this->_is_comment ;	}	public function getIs_at(){		return $this->_is_at ;	}	public function getRepost_url(){		return $this->_repost_url ;	}	public function getWb_content(){		return $this->_wb_content ;	}	public function getWb_img(){		return $this->_wb_img ;	}	public function getAt_num(){		return $this->_at_num ;	}	public function getUnit_price(){		return $this->_unit_price ;	}	public function getAssign(){		return $this->_assign ;	}	public function getPay_amount(){		return $this->_pay_amount ;	}	public function getFans_count(){		return $this->_fans_count ;	}	public function getIs_repost(){		return $this->_is_repost ;	}	public function getWhere(){		return $this->_where ;	}	public function getCache_config() {		return $this->_cache_config;	}
	public function setWbzf_id($value){		$this->_wbzf_id = $value;	}	public function setTask_id($value){		$this->_task_id = $value;	}	public function setWb_platform($value){		$this->_wb_platform = $value;	}	public function setIs_focus($value){		$this->_is_focus = $value;	}	public function setIs_comment($value){		$this->_is_comment = $value;	}	public function setIs_at($value){		$this->_is_at = $value;	}	public function setRepost_url($value){		$this->_repost_url = $value;	}	public function setWb_content($value){		$this->_wb_content = $value;	}	public function setWb_img($value){		$this->_wb_img = $value;	}	public function setAt_num($value){		$this->_at_num = $value;	}	public function setUnit_price($value){		$this->_unit_price = $value;	}	public function setAssign($value){		$this->_assign = $value;	}	public function setPay_amount($value){		$this->_pay_amount = $value;	}	public function setFans_count($value){		$this->_fans_count = $value;	}	public function setIs_repost($value){		$this->_is_repost = $value;	}	public function setWhere($value){		$this->_where = $value;	}	public function setCache_config($_cache_config) {		$this->_cache_config = $_cache_config;	}
	public  function __set($property_name, $value) {
		$this->$property_name = $value;
	}
	public function __get($property_name) {
		if (isset ( $this->$property_name )) {
			return $this->$property_name;
		} else {
			return null;
		}
	}
		function create_keke_witkey_task_wbzf(){		$data =  array();		if(!is_null($this->_wbzf_id)){			$data['wbzf_id']=$this->_wbzf_id;		}		if(!is_null($this->_task_id)){			$data['task_id']=$this->_task_id;		}		if(!is_null($this->_wb_platform)){			$data['wb_platform']=$this->_wb_platform;		}		if(!is_null($this->_is_focus)){			$data['is_focus']=$this->_is_focus;		}		if(!is_null($this->_is_comment)){			$data['is_comment']=$this->_is_comment;		}		if(!is_null($this->_is_at)){			$data['is_at']=$this->_is_at;		}		if(!is_null($this->_repost_url)){			$data['repost_url']=$this->_repost_url;		}		if(!is_null($this->_wb_content)){			$data['wb_content']=$this->_wb_content;		}		if(!is_null($this->_wb_img)){			$data['wb_img']=$this->_wb_img;		}		if(!is_null($this->_at_num)){			$data['at_num']=$this->_at_num;		}		if(!is_null($this->_unit_price)){			$data['unit_price']=$this->_unit_price;		}		if(!is_null($this->_assign)){			$data['assign']=$this->_assign;		}		if(!is_null($this->_pay_amount)){			$data['pay_amount']=$this->_pay_amount;		}		if(!is_null($this->_fans_count)){			$data['fans_count']=$this->_fans_count;		}		if(!is_null($this->_is_repost)){			$data['is_repost']=$this->_is_repost;		}		return $this->_wbzf_id = $this->_db->inserttable($this->_tablename,$data,1,$this->_replace);	}
		function edit_keke_witkey_task_wbzf(){		$data =  array();		if(!is_null($this->_wbzf_id)){			$data['wbzf_id']=$this->_wbzf_id;		}		if(!is_null($this->_task_id)){			$data['task_id']=$this->_task_id;		}		if(!is_null($this->_wb_platform)){			$data['wb_platform']=$this->_wb_platform;		}		if(!is_null($this->_is_focus)){			$data['is_focus']=$this->_is_focus;		}		if(!is_null($this->_is_comment)){			$data['is_comment']=$this->_is_comment;		}		if(!is_null($this->_is_at)){			$data['is_at']=$this->_is_at;		}		if(!is_null($this->_repost_url)){			$data['repost_url']=$this->_repost_url;		}		if(!is_null($this->_wb_content)){			$data['wb_content']=$this->_wb_content;		}		if(!is_null($this->_wb_img)){			$data['wb_img']=$this->_wb_img;		}		if(!is_null($this->_at_num)){			$data['at_num']=$this->_at_num;		}		if(!is_null($this->_unit_price)){			$data['unit_price']=$this->_unit_price;		}		if(!is_null($this->_assign)){			$data['assign']=$this->_assign;		}		if(!is_null($this->_pay_amount)){			$data['pay_amount']=$this->_pay_amount;		}		if(!is_null($this->_fans_count)){			$data['fans_count']=$this->_fans_count;		}		if(!is_null($this->_is_repost)){			$data['is_repost']=$this->_is_repost;		}		if($this->_where){			return $this->_db->updatetable($this->_tablename,$data,$this->getWhere());		}		else{			$where = array('wbzf_id' => $this->_wbzf_id);			return $this->_db->updatetable($this->_tablename,$data,$where);		}	}
		function query_keke_witkey_task_wbzf($is_cache=0, $cache_time=0){		if($this->_where){			$sql = "select * from $this->_tablename where ".$this->_where;		}		else{			$sql = "select * from $this->_tablename";		}		if ($is_cache) {			$this->_cache_config ['is_cache'] = $is_cache;		}		if ($cache_time) {			$this->_cache_config ['time'] = $cache_time;		}		if ($this->_cache_config ['is_cache']) {			if (CACHE_TYPE) {				$keke_cache = new keke_cache_class ( CACHE_TYPE );				$id = $this->_tablename . ($this->_where?"_" .substr(md5 ( $this->_where ),0,6):'');				$data = $keke_cache->get ( $id );				if ($data) {					return $data;				} else {					$res = $this->_dbop->query ( $sql );					$keke_cache->set ( $id, $res,$this->_cache_config['time'] );					$this->_where = "";					return $res;				}			}		}else{			$this->_where = "";			return  $this->_dbop->query ( $sql );		}	}
		function count_keke_witkey_task_wbzf(){		if($this->_where){			$sql = "select count(*) as count from $this->_tablename where ".$this->_where;		}		else{			$sql = "select count(*) as count from $this->_tablename";		}		$this->_where = "";		return $this->_dbop->getCount($sql);	}
		function del_keke_witkey_task_wbzf(){		if($this->_where){			$sql = "delete from $this->_tablename where ".$this->_where;		}		else{			$sql = "delete from $this->_tablename where wbzf_id = $this->_wbzf_id ";		}		$this->_where = "";		return $this->_dbop->execute($sql);	}
}
?>