<?php
class Keke_witkey_model_class{
	public $_db;
	public $_tablename;
	public $_dbop;
	public $_model_id;	public $_model_code;	public $_model_name;	public $_model_dir;	public $_model_type;	public $_model_dev;	public $_model_status;	public $_model_desc;	public $_on_time;	public $_hide_mode;	public $_listorder;	public $_model_intro;	public $_indus_bid;	public $_config;
	public $_cache_config = array ('is_cache' => 0, 'time' => 0 );
	public $_replace=0;
	public $_where;
	function  keke_witkey_model_class(){		$this->_db = new db_factory ( );		$this->_dbop = $this->_db->create(DBTYPE);		$this->_tablename = TABLEPRE."witkey_model";	}
	public function getModel_id(){		return $this->_model_id ;	}	public function getModel_code(){		return $this->_model_code ;	}	public function getModel_name(){		return $this->_model_name ;	}	public function getModel_dir(){		return $this->_model_dir ;	}	public function getModel_type(){		return $this->_model_type ;	}	public function getModel_dev(){		return $this->_model_dev ;	}	public function getModel_status(){		return $this->_model_status ;	}	public function getModel_desc(){		return $this->_model_desc ;	}	public function getOn_time(){		return $this->_on_time ;	}	public function getHide_mode(){		return $this->_hide_mode ;	}	public function getListorder(){		return $this->_listorder ;	}	public function getModel_intro(){		return $this->_model_intro ;	}	public function getIndus_bid(){		return $this->_indus_bid ;	}	public function getConfig(){		return $this->_config ;	}	public function getWhere(){		return $this->_where ;	}	public function getCache_config() {		return $this->_cache_config;	}
	public function setModel_id($value){		$this->_model_id = $value;	}	public function setModel_code($value){		$this->_model_code = $value;	}	public function setModel_name($value){		$this->_model_name = $value;	}	public function setModel_dir($value){		$this->_model_dir = $value;	}	public function setModel_type($value){		$this->_model_type = $value;	}	public function setModel_dev($value){		$this->_model_dev = $value;	}	public function setModel_status($value){		$this->_model_status = $value;	}	public function setModel_desc($value){		$this->_model_desc = $value;	}	public function setOn_time($value){		$this->_on_time = $value;	}	public function setHide_mode($value){		$this->_hide_mode = $value;	}	public function setListorder($value){		$this->_listorder = $value;	}	public function setModel_intro($value){		$this->_model_intro = $value;	}	public function setIndus_bid($value){		$this->_indus_bid = $value;	}	public function setConfig($value){		$this->_config = $value;	}	public function setWhere($value){		$this->_where = $value;	}	public function setCache_config($_cache_config) {		$this->_cache_config = $_cache_config;	}
	public  function __set($property_name, $value) {
		$this->$property_name = $value;
	}
	public function __get($property_name) {
		if (isset ( $this->$property_name )) {
			return $this->$property_name;
		} else {
			return null;
		}
	}
		function create_keke_witkey_model(){		$data =  array();		if(!is_null($this->_model_id)){			$data['model_id']=$this->_model_id;		}		if(!is_null($this->_model_code)){			$data['model_code']=$this->_model_code;		}		if(!is_null($this->_model_name)){			$data['model_name']=$this->_model_name;		}		if(!is_null($this->_model_dir)){			$data['model_dir']=$this->_model_dir;		}		if(!is_null($this->_model_type)){			$data['model_type']=$this->_model_type;		}		if(!is_null($this->_model_dev)){			$data['model_dev']=$this->_model_dev;		}		if(!is_null($this->_model_status)){			$data['model_status']=$this->_model_status;		}		if(!is_null($this->_model_desc)){			$data['model_desc']=$this->_model_desc;		}		if(!is_null($this->_on_time)){			$data['on_time']=$this->_on_time;		}		if(!is_null($this->_hide_mode)){			$data['hide_mode']=$this->_hide_mode;		}		if(!is_null($this->_listorder)){			$data['listorder']=$this->_listorder;		}		if(!is_null($this->_model_intro)){			$data['model_intro']=$this->_model_intro;		}		if(!is_null($this->_indus_bid)){			$data['indus_bid']=$this->_indus_bid;		}		if(!is_null($this->_config)){			$data['config']=$this->_config;		}		return $this->_model_id = $this->_db->inserttable($this->_tablename,$data,1,$this->_replace);	}
		function edit_keke_witkey_model(){		$data =  array();		if(!is_null($this->_model_id)){			$data['model_id']=$this->_model_id;		}		if(!is_null($this->_model_code)){			$data['model_code']=$this->_model_code;		}		if(!is_null($this->_model_name)){			$data['model_name']=$this->_model_name;		}		if(!is_null($this->_model_dir)){			$data['model_dir']=$this->_model_dir;		}		if(!is_null($this->_model_type)){			$data['model_type']=$this->_model_type;		}		if(!is_null($this->_model_dev)){			$data['model_dev']=$this->_model_dev;		}		if(!is_null($this->_model_status)){			$data['model_status']=$this->_model_status;		}		if(!is_null($this->_model_desc)){			$data['model_desc']=$this->_model_desc;		}		if(!is_null($this->_on_time)){			$data['on_time']=$this->_on_time;		}		if(!is_null($this->_hide_mode)){			$data['hide_mode']=$this->_hide_mode;		}		if(!is_null($this->_listorder)){			$data['listorder']=$this->_listorder;		}		if(!is_null($this->_model_intro)){			$data['model_intro']=$this->_model_intro;		}		if(!is_null($this->_indus_bid)){			$data['indus_bid']=$this->_indus_bid;		}		if(!is_null($this->_config)){			$data['config']=$this->_config;		}		if($this->_where){			return $this->_db->updatetable($this->_tablename,$data,$this->getWhere());		}		else{			$where = array('model_id' => $this->_model_id);			return $this->_db->updatetable($this->_tablename,$data,$where);		}	}
		function query_keke_witkey_model($is_cache=0, $cache_time=0){		if($this->_where){			$sql = "select * from $this->_tablename where ".$this->_where;		}		else{			$sql = "select * from $this->_tablename";		}		if ($is_cache) {			$this->_cache_config ['is_cache'] = $is_cache;		}		if ($cache_time) {			$this->_cache_config ['time'] = $cache_time;		}		if ($this->_cache_config ['is_cache']) {			if (CACHE_TYPE) {				$keke_cache = new keke_cache_class ( CACHE_TYPE );				$id = $this->_tablename . ($this->_where?"_" .substr(md5 ( $this->_where ),0,6):'');				$data = $keke_cache->get ( $id );				if ($data) {					return $data;				} else {					$res = $this->_dbop->query ( $sql );					$keke_cache->set ( $id, $res,$this->_cache_config['time'] );					$this->_where = "";					return $res;				}			}		}else{			$this->_where = "";			return  $this->_dbop->query ( $sql );		}	}
		function count_keke_witkey_model(){		if($this->_where){			$sql = "select count(*) as count from $this->_tablename where ".$this->_where;		}		else{			$sql = "select count(*) as count from $this->_tablename";		}		$this->_where = "";		return $this->_dbop->getCount($sql);	}
		function del_keke_witkey_model(){		if($this->_where){			$sql = "delete from $this->_tablename where ".$this->_where;		}		else{			$sql = "delete from $this->_tablename where model_id = $this->_model_id ";		}		$this->_where = "";		return $this->_dbop->execute($sql);	}
}
?>