<?php
class Keke_witkey_auth_item_class{
	public $_db;
	public $_tablename;
	public $_dbop;
	public $_auth_code;	public $_auth_title;	public $_auth_day;	public $_auth_small_ico;	public $_auth_small_n_ico;	public $_auth_big_ico;	public $_auth_desc;	public $_auth_cash;	public $_auth_expir;	public $_auth_open;	public $_auth_show;	public $_muti_auth;	public $_update_time;	public $_auth_dir;	public $_listorder;	public $_config;
	public $_cache_config = array ('is_cache' => 0, 'time' => 0 );
	public $_replace=0;
	public $_where;
	function  keke_witkey_auth_item_class(){		$this->_db = new db_factory ( );		$this->_dbop = $this->_db->create(DBTYPE);		$this->_tablename = TABLEPRE."witkey_auth_item";	}	 
	public function getAuth_code(){		return $this->_auth_code ;	}	public function getAuth_title(){		return $this->_auth_title ;	}	public function getAuth_day(){		return $this->_auth_day ;	}	public function getAuth_small_ico(){		return $this->_auth_small_ico ;	}	public function getAuth_small_n_ico(){		return $this->_auth_small_n_ico ;	}	public function getAuth_big_ico(){		return $this->_auth_big_ico ;	}	public function getAuth_desc(){		return $this->_auth_desc ;	}	public function getAuth_cash(){		return $this->_auth_cash ;	}	public function getAuth_expir(){		return $this->_auth_expir ;	}	public function getAuth_open(){		return $this->_auth_open ;	}	public function getAuth_show(){		return $this->_auth_show ;	}	public function getMuti_auth(){		return $this->_muti_auth ;	}	public function getUpdate_time(){		return $this->_update_time ;	}	public function getAuth_dir(){		return $this->_auth_dir ;	}	public function getListorder(){		return $this->_listorder ;	}	public function getConfig(){		return $this->_config ;	}	public function getWhere(){		return $this->_where ;	}	public function getCache_config() {		return $this->_cache_config;	}
	public function setAuth_code($value){		$this->_auth_code = $value;	}	public function setAuth_title($value){		$this->_auth_title = $value;	}	public function setAuth_day($value){		$this->_auth_day = $value;	}	public function setAuth_small_ico($value){		$this->_auth_small_ico = $value;	}	public function setAuth_small_n_ico($value){		$this->_auth_small_n_ico = $value;	}	public function setAuth_big_ico($value){		$this->_auth_big_ico = $value;	}	public function setAuth_desc($value){		$this->_auth_desc = $value;	}	public function setAuth_cash($value){		$this->_auth_cash = $value;	}	public function setAuth_expir($value){		$this->_auth_expir = $value;	}	public function setAuth_open($value){		$this->_auth_open = $value;	}	public function setAuth_show($value){		$this->_auth_show = $value;	}	public function setMuti_auth($value){		$this->_muti_auth = $value;	}	public function setUpdate_time($value){		$this->_update_time = $value;	}	public function setAuth_dir($value){		$this->_auth_dir = $value;	}	public function setListorder($value){		$this->_listorder = $value;	}	public function setConfig($value){		$this->_config = $value;	}	public function setWhere($value){		$this->_where = $value;	}	public function setCache_config($_cache_config) {		$this->_cache_config = $_cache_config;	}
	public  function __set($property_name, $value) {
		$this->$property_name = $value;
	}
	public function __get($property_name) {
		if (isset ( $this->$property_name )) {
			return $this->$property_name;
		} else {
			return null;
		}
	}
		function create_keke_witkey_auth_item(){		$data =  array();		if(!is_null($this->_auth_code)){			$data['auth_code']=$this->_auth_code;		}		if(!is_null($this->_auth_title)){			$data['auth_title']=$this->_auth_title;		}		if(!is_null($this->_auth_day)){			$data['auth_day']=$this->_auth_day;		}		if(!is_null($this->_auth_small_ico)){			$data['auth_small_ico']=$this->_auth_small_ico;		}		if(!is_null($this->_auth_small_n_ico)){			$data['auth_small_n_ico']=$this->_auth_small_n_ico;		}		if(!is_null($this->_auth_big_ico)){			$data['auth_big_ico']=$this->_auth_big_ico;		}		if(!is_null($this->_auth_desc)){			$data['auth_desc']=$this->_auth_desc;		}		if(!is_null($this->_auth_cash)){			$data['auth_cash']=$this->_auth_cash;		}		if(!is_null($this->_auth_expir)){			$data['auth_expir']=$this->_auth_expir;		}		if(!is_null($this->_auth_open)){			$data['auth_open']=$this->_auth_open;		}		if(!is_null($this->_auth_show)){			$data['auth_show']=$this->_auth_show;		}		if(!is_null($this->_muti_auth)){			$data['muti_auth']=$this->_muti_auth;		}		if(!is_null($this->_update_time)){			$data['update_time']=$this->_update_time;		}		if(!is_null($this->_auth_dir)){			$data['auth_dir']=$this->_auth_dir;		}		if(!is_null($this->_listorder)){			$data['listorder']=$this->_listorder;		}		if(!is_null($this->_config)){			$data['config']=$this->_config;		}		return $this->_auth_code = $this->_db->inserttable($this->_tablename,$data,1,$this->_replace);	}
		function edit_keke_witkey_auth_item(){		$data =  array();		if(!is_null($this->_auth_code)){			$data['auth_code']=$this->_auth_code;		}		if(!is_null($this->_auth_title)){			$data['auth_title']=$this->_auth_title;		}		if(!is_null($this->_auth_day)){			$data['auth_day']=$this->_auth_day;		}		if(!is_null($this->_auth_small_ico)){			$data['auth_small_ico']=$this->_auth_small_ico;		}		if(!is_null($this->_auth_small_n_ico)){			$data['auth_small_n_ico']=$this->_auth_small_n_ico;		}		if(!is_null($this->_auth_big_ico)){			$data['auth_big_ico']=$this->_auth_big_ico;		}		if(!is_null($this->_auth_desc)){			$data['auth_desc']=$this->_auth_desc;		}		if(!is_null($this->_auth_cash)){			$data['auth_cash']=$this->_auth_cash;		}		if(!is_null($this->_auth_expir)){			$data['auth_expir']=$this->_auth_expir;		}		if(!is_null($this->_auth_open)){			$data['auth_open']=$this->_auth_open;		}		if(!is_null($this->_auth_show)){			$data['auth_show']=$this->_auth_show;		}		if(!is_null($this->_muti_auth)){			$data['muti_auth']=$this->_muti_auth;		}		if(!is_null($this->_update_time)){			$data['update_time']=$this->_update_time;		}		if(!is_null($this->_auth_dir)){			$data['auth_dir']=$this->_auth_dir;		}		if(!is_null($this->_listorder)){			$data['listorder']=$this->_listorder;		}		if(!is_null($this->_config)){			$data['config']=$this->_config;		}		if($this->_where){			return $this->_db->updatetable($this->_tablename,$data,$this->getWhere());		}		else{			$where = array('auth_code' => $this->_auth_code);			return $this->_db->updatetable($this->_tablename,$data,$where);		}	}
		function query_keke_witkey_auth_item($is_cache=0, $cache_time=0){		if($this->_where){			$sql = "select * from $this->_tablename where ".$this->_where;		}		else{			$sql = "select * from $this->_tablename";		}		if ($is_cache) {			$this->_cache_config ['is_cache'] = $is_cache;		}		if ($cache_time) {			$this->_cache_config ['time'] = $cache_time;		}		if ($this->_cache_config ['is_cache']) {			if (CACHE_TYPE) {				$keke_cache = new keke_cache_class ( CACHE_TYPE );				$id = $this->_tablename . ($this->_where?"_" .substr(md5 ( $this->_where ),0,6):'');				$data = $keke_cache->get ( $id );				if ($data) {					return $data;				} else {					$res = $this->_dbop->query ( $sql );					$keke_cache->set ( $id, $res,$this->_cache_config['time'] );					$this->_where = "";					return $res;				}			}		}else{			$this->_where = "";			return  $this->_dbop->query ( $sql );		}	}
		function count_keke_witkey_auth_item(){		if($this->_where){			$sql = "select count(*) as count from $this->_tablename where ".$this->_where;		}		else{			$sql = "select count(*) as count from $this->_tablename";		}		$this->_where = "";		return $this->_dbop->getCount($sql);	}
		function del_keke_witkey_auth_item(){		if($this->_where){			$sql = "delete from $this->_tablename where ".$this->_where;		}		else{			$sql = "delete from $this->_tablename where auth_code = $this->_auth_code ";		}		$this->_where = "";		return $this->_dbop->execute($sql);	}
}
?>