<?php
  class Keke_witkey_order_class{
        public $_db;
        public $_tablename;
	    public $_dbop;
	    	 public $_order_id;  		 public $_order_name; 		 public $_order_time; 		 public $_order_amount; 		 public $_order_status; 		 public $_order_body; 		 public $_order_uid; 		 public $_order_username; 		 public $_seller_uid; 		 public $_seller_username; 		 public $_model_id; 		 public $_to_seller_message; 		 public $_ys_end_time; 		 public $_service_end_time; 
	    public $_cache_config = array ('is_cache' => 0, 'time' => 0 );
	    public $_replace=0;  
	    public $_where;      
	     function  keke_witkey_order_class(){ 			 $this->_db = new db_factory ( );			 $this->_dbop = $this->_db->create(DBTYPE);			 $this->_tablename = TABLEPRE."witkey_order";		 }	    
	    		public function getOrder_id(){			 return $this->_order_id ;		}		public function getOrder_name(){			 return $this->_order_name ;		}		public function getOrder_time(){			 return $this->_order_time ;		}		public function getOrder_amount(){			 return $this->_order_amount ;		}		public function getOrder_status(){			 return $this->_order_status ;		}		public function getOrder_body(){			 return $this->_order_body ;		}		public function getOrder_uid(){			 return $this->_order_uid ;		}		public function getOrder_username(){			 return $this->_order_username ;		}		public function getSeller_uid(){			 return $this->_seller_uid ;		}		public function getSeller_username(){			 return $this->_seller_username ;		}		public function getModel_id(){			 return $this->_model_id ;		}		public function getTo_seller_message(){			 return $this->_to_seller_message ;		}		public function getYs_end_time(){			 return $this->_ys_end_time ;		}		public function getService_end_time(){			 return $this->_service_end_time ;		}		public function getWhere(){			 return $this->_where ;		}		public function getCache_config() {			return $this->_cache_config;		}
	    		public function setOrder_id($value){ 			 $this->_order_id = $value;		}		public function setOrder_name($value){ 			 $this->_order_name = $value;		}		public function setOrder_time($value){ 			 $this->_order_time = $value;		}		public function setOrder_amount($value){ 			 $this->_order_amount = $value;		}		public function setOrder_status($value){ 			 $this->_order_status = $value;		}		public function setOrder_body($value){ 			 $this->_order_body = $value;		}		public function setOrder_uid($value){ 			 $this->_order_uid = $value;		}		public function setOrder_username($value){ 			 $this->_order_username = $value;		}		public function setSeller_uid($value){ 			 $this->_seller_uid = $value;		}		public function setSeller_username($value){ 			 $this->_seller_username = $value;		}		public function setModel_id($value){ 			 $this->_model_id = $value;		}		public function setTo_seller_message($value){ 			 $this->_to_seller_message = $value;		}		public function setYs_end_time($value){ 			 $this->_ys_end_time = $value;		}		public function setService_end_time($value){ 			 $this->_service_end_time = $value;		}		public function setWhere($value){ 			 $this->_where = $value;		}		public function setCache_config($_cache_config) {			 $this->_cache_config = $_cache_config; 		}
    	   public  function __set($property_name, $value) {
		 		$this->$property_name = $value; 
			}
			public function __get($property_name) { 
				if (isset ( $this->$property_name )) { 
					return $this->$property_name; 
				} else { 
					return null; 
				} 
			}
	    		function create_keke_witkey_order(){		 		 $data =  array(); 					if(!is_null($this->_order_id)){ 				 $data['order_id']=$this->_order_id;			}			if(!is_null($this->_order_name)){ 				 $data['order_name']=$this->_order_name;			}			if(!is_null($this->_order_time)){ 				 $data['order_time']=$this->_order_time;			}			if(!is_null($this->_order_amount)){ 				 $data['order_amount']=$this->_order_amount;			}			if(!is_null($this->_order_status)){ 				 $data['order_status']=$this->_order_status;			}			if(!is_null($this->_order_body)){ 				 $data['order_body']=$this->_order_body;			}			if(!is_null($this->_order_uid)){ 				 $data['order_uid']=$this->_order_uid;			}			if(!is_null($this->_order_username)){ 				 $data['order_username']=$this->_order_username;			}			if(!is_null($this->_seller_uid)){ 				 $data['seller_uid']=$this->_seller_uid;			}			if(!is_null($this->_seller_username)){ 				 $data['seller_username']=$this->_seller_username;			}			if(!is_null($this->_model_id)){ 				 $data['model_id']=$this->_model_id;			}			if(!is_null($this->_to_seller_message)){ 				 $data['to_seller_message']=$this->_to_seller_message;			}			if(!is_null($this->_ys_end_time)){ 				 $data['ys_end_time']=$this->_ys_end_time;			}			if(!is_null($this->_service_end_time)){ 				 $data['service_end_time']=$this->_service_end_time;			}			 return $this->_order_id = $this->_db->inserttable($this->_tablename,$data,1,$this->_replace); 		 } 
	    		function edit_keke_witkey_order(){ 		 		 $data =  array();  					if(!is_null($this->_order_id)){ 				 $data['order_id']=$this->_order_id;			}			if(!is_null($this->_order_name)){ 				 $data['order_name']=$this->_order_name;			}			if(!is_null($this->_order_time)){ 				 $data['order_time']=$this->_order_time;			}			if(!is_null($this->_order_amount)){ 				 $data['order_amount']=$this->_order_amount;			}			if(!is_null($this->_order_status)){ 				 $data['order_status']=$this->_order_status;			}			if(!is_null($this->_order_body)){ 				 $data['order_body']=$this->_order_body;			}			if(!is_null($this->_order_uid)){ 				 $data['order_uid']=$this->_order_uid;			}			if(!is_null($this->_order_username)){ 				 $data['order_username']=$this->_order_username;			}			if(!is_null($this->_seller_uid)){ 				 $data['seller_uid']=$this->_seller_uid;			}			if(!is_null($this->_seller_username)){ 				 $data['seller_username']=$this->_seller_username;			}			if(!is_null($this->_model_id)){ 				 $data['model_id']=$this->_model_id;			}			if(!is_null($this->_to_seller_message)){ 				 $data['to_seller_message']=$this->_to_seller_message;			}			if(!is_null($this->_ys_end_time)){ 				 $data['ys_end_time']=$this->_ys_end_time;			}			if(!is_null($this->_service_end_time)){ 				 $data['service_end_time']=$this->_service_end_time;			}			if($this->_where){ 				 return $this->_db->updatetable($this->_tablename,$data,$this->getWhere()); 			 } 			 else{ 				 $where = array('order_id' => $this->_order_id); 				 return $this->_db->updatetable($this->_tablename,$data,$where); 			} 		 } 
	    		function query_keke_witkey_order($is_cache=0, $cache_time=0){ 			 if($this->_where){ 				 $sql = "select * from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "select * from $this->_tablename"; 			 } 			if ($is_cache) {			 $this->_cache_config ['is_cache'] = $is_cache;			}			if ($cache_time) {			 $this->_cache_config ['time'] = $cache_time;			 }			 if ($this->_cache_config ['is_cache']) {			     if (CACHE_TYPE) {					 $keke_cache = new keke_cache_class ( CACHE_TYPE );					 $id = $this->_tablename . ($this->_where?"_" .substr(md5 ( $this->_where ),0,6):'');						$data = $keke_cache->get ( $id );							if ($data) {								return $data; 							} else { 								$res = $this->_dbop->query ( $sql ); 								$keke_cache->set ( $id, $res,$this->_cache_config['time'] ); 					 			$this->_where = ""; 								return $res; 							} 						} 			 }else{			 	$this->_where = ""; 				return  $this->_dbop->query ( $sql ); 			 }		 } 
	    		function count_keke_witkey_order(){ 			 if($this->_where){ 				 $sql = "select count(*) as count from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "select count(*) as count from $this->_tablename"; 			 } 			 $this->_where = ""; 			 return $this->_dbop->getCount($sql); 		 } 
	    		function del_keke_witkey_order(){ 			 if($this->_where){ 				 $sql = "delete from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "delete from $this->_tablename where order_id = $this->_order_id "; 			 } 			 $this->_where = ""; 			 return $this->_dbop->execute($sql); 		 } 
   }
 ?>